Added SYCLomatic-test, SYCLomatic, distributed-ranges, level-zero-tests, oneAPI-samples, oneMKL, and oneapi-ci
Be-Secure/besecure-assessment-datastore pull request #153
Opened 2023-04-07 18:58 UTC by sudhirverma

2023-04-10 06:59 UTC, asa1997 commented on distributed-ranges/old-mpi-model/sast/distributed-ranges-old-mpi-model-sonarqube-report.json
@sudhirverma No data present in this report.

2023-04-10 07:02 UTC, asa1997 commented on oneAPI-samples/2023.0.0/scorecard/oneAPI-samples-2023.0.0-scorecard-report.json
@sudhirverma Please check if this is the correct report.

2023-04-10 07:03 UTC, asa1997 commented on oneMKL/v0.1/sbom/oneMKL-v0.1-sbom-report.json
@sudhirverma Please try to generate sbom using spdx for these cases.

2023-04-10 07:04 UTC, asa1997 commented on oneapi-ci/alpha/sast/oneapi-ci-alpha-sonarqube-report.json
@sudhirverma This report is empty.

2023-04-10 07:04 UTC, asa1997 requested changes
@sudhirverma Please address the comments.

2023-04-10 16:06 UTC, sudhirverma commented on distributed-ranges/old-mpi-model/sast/distributed-ranges-old-mpi-model-sonarqube-report.json
No report found by sonarqube

2023-04-11 06:04 UTC, sudhirverma commented on oneAPI-samples/2023.0.0/scorecard/oneAPI-samples-2023.0.0-scorecard-report.json
I will update the scorecard report

2023-04-11 06:04 UTC, sudhirverma commented on oneMKL/v0.1/sbom/oneMKL-v0.1-sbom-report.json
spdx doesn't support CPP language

2023-04-11 06:18 UTC, sudhirverma commented on oneapi-ci/alpha/sast/oneapi-ci-alpha-sonarqube-report.json
yes sonarqube doesn't doesn't find any Vulnerabilities

2023-05-03 11:50 UTC, asa1997 commented on distributed-ranges/old-mpi-model/sast/distributed-ranges-old-mpi-model-sonarqube-report.json
If nothing was found by sonarqube, we dont have to add it

2023-05-03 11:51 UTC, asa1997 commented on oneapi-ci/alpha/sast/oneapi-ci-alpha-sonarqube-report.json
Please remove the empty reports

2023-05-03 11:51 UTC, asa1997 requested changes
@sudhirverma Please remove the empty reports

2023-05-03 14:14 UTC, asa1997 approved these changes
@sudhirverma LGTM

2023-05-03 14:14 UTC, merged