uploading assessment reports
Be-Secure/besecure-assessment-datastore pull request #172
Opened 2023-09-22 15:14 UTC by sand-hya

[pytorch #174](https://github.com/Be-Secure/Be-Secure/issues/174)
[tensorflow #133](https://github.com/Be-Secure/Be-Secure/issues/133)
[adversarial-robustness-toolbox #437](https://github.com/Be-Secure/Be-Secure/issues/437)

2023-11-02 16:52 UTC, sudhirverma commented on pytorch/v2.1.0-rc5/criticality_score/pytorch-v2.1.0-rc5-criticality_score-report.json
> +    "contributor_count": 4301,
I don't see pytorch in osspoi

2023-11-03 06:23 UTC, sand-hya commented on pytorch/v2.1.0-rc5/criticality_score/pytorch-v2.1.0-rc5-criticality_score-report.json
> +    "contributor_count": 4301,
i have added pytorch and raised a new PR for that as there were conflicts

2023-11-22 09:47 UTC, sudhirverma requested changes

2023-11-22 09:47 UTC, sudhirverma commented on elasticsearch/v8.10.4/scorecard/elasticsearch-v8.10.4-scorecard-report.json
> +      },
diffusers report is not vissible

2023-11-22 12:08 UTC, sudhirverma approved these changes

2023-11-22 12:08 UTC, merged