Added Assessment Reports
Be-Secure/besecure-assessment-datastore pull request #199
Opened 2024-01-31 06:07 UTC by Aditi8007

crityicality-score for below project
#spring-boot
#opstrace
#spring-security
#oyente
#privacyidea
#diffusers
#spring-data-jpa
#spring-session
#spring-data-mongodb

All reports for this project
#Node
#Mythril
#Syntest-solidity
#Viagrunts
#Langchain

2024-02-06 05:08 UTC, sudhirverma requested changes

2024-02-06 05:08 UTC, sudhirverma commented on TheHive/4.1.24/criticality_score/TheHive-4.1.24-criticality_score-report.json
> -    "url": "https://github.com/Be-Secure/TheHive",
why have you deleted this report?

2024-02-06 05:08 UTC, sudhirverma commented on ort/12.0.0/scorecard/ort-12.0.0-scorecard-report.json
> +  "repo": {
this version is not available in BeSLighthouse

2024-02-06 09:45 UTC, Aditi8007 commented on TheHive/4.1.24/criticality_score/TheHive-4.1.24-criticality_score-report.json
> -    "url": "https://github.com/Be-Secure/TheHive",
Added plz check

2024-02-06 09:46 UTC, Aditi8007 commented on ort/12.0.0/scorecard/ort-12.0.0-scorecard-report.json
> +  "repo": {
I removed this  version.
plz check

2024-02-08 11:01 UTC, sudhirverma approved these changes

2024-02-08 11:02 UTC, merged