codeql for Canvas-LMS-Release-2023-03-15.23
Be-Secure/besecure-assessment-datastore pull request #70
Opened 2023-03-03 07:51 UTC by Aditi8007

2023-03-03 10:14 UTC, sudhirverma reviewed
Please add criticality_score too.

2023-03-09 04:52 UTC, sudhirverma requested changes

2023-03-09 04:52 UTC, sudhirverma commented on canvas-lms/release-2023-03-15.23/sast/canvas-lms-release-2023-03-15.23-codeql-report.json
> +{\rtf1\ansi\ansicpg1252\cocoartf2639
@Aditi8007 this is not a proper json format

2023-03-09 04:52 UTC, sudhirverma commented on pimcore/10.1.0/scorecard/pimcore-v10.1.0-scorecard-report.json
> +{
can you fix the version detail you have created 10.1.0 version folder and in file you have use v10.1.0

2023-03-09 12:00 UTC, asa1997 reviewed
@Aditi8007 @harimohanr Duplicate pr. Hence closing.

2023-03-09 12:00 UTC, closed without merging