fixed json formate for Canvas -lms
Be-Secure/besecure-assessment-datastore pull request #71
Opened 2023-03-03 08:43 UTC by Aditi8007

https://github.com/Be-Secure/BeSLighthouse/issues/160 fixed json formate

2023-03-03 10:13 UTC, sudhirverma reviewed
LGTM can you please add criticality_score too.

2023-03-07 04:02 UTC, sudhirverma requested changes

2023-03-07 04:02 UTC, sudhirverma commented on canvas-android/teacher-1.19.0-52/criticality_score/canvas-android-teacher-1.19.0-52-criticality -score.json
> +{
@Aditi8007 can you check file name is correct I see space after criticality

canvas-android-teacher-1.19.0-52-criticality -score.json

2023-03-07 04:02 UTC, sudhirverma commented on canvas-lms/release-2023-03-15.23/criticality_score/canvas-lms-release-2023-03-15.23-criticality -score.json
> +{
same here

2023-03-07 04:02 UTC, sudhirverma commented on kaa/1.4.13/criticality_score/kaa-1.4.13-criticality -score.json
> +    "name": "kaa",
same here

2023-03-07 04:02 UTC, sudhirverma commented on pimcore/10.1.0/criticality_score/pimcore-v10.1.0-criticality -score.json
> +    "url": "https://github.com/Be-Secure/pimcore",
same here

2023-03-07 04:02 UTC, sudhirverma commented on ros/1.15.7/criticality_score/ros-1.15.7-criticality -score.json
> +    "url": "https://github.com/Be-Secure/ros",
same here

2023-03-07 08:46 UTC, sudhirverma requested changes

2023-03-07 08:46 UTC, sudhirverma commented on canvas-android/teacher-1.19.0-52/criticality_score/canvas-android-teacher-1.19.0-52-criticality-score.json
> +{
You are creating the duplicate report

2023-03-09 11:58 UTC, asa1997 approved these changes
@Aditi8007 @harimohanr LGTM

2023-03-09 11:58 UTC, merged